feat: Completed the Html for Account Management & Updated CSS files.
DevOps2023TeamD/TeamD_Assignment pull request #38
Opened 2024-01-19 13:12 UTC by Jkqx

The Backend needs to be touched up. Be sure to include these lines:
{% for acc in accounts %}

2024-01-19 13:49 UTC, YaSwe requested changes
Values in account management table are hardcoded. A status column can be added.

2024-01-19 17:23 UTC, Jkqx commented
I reverted commit 129f856 due to committing the wrong files in.

2024-01-19 17:45 UTC, Jkqx commented
This commit has satisfy the requirement you need @YaSwe.

2024-01-20 05:31 UTC, YaSwe approved these changes

2024-01-20 05:32 UTC, merged